global:
  configMapNameOverride:
    env: mutualize-prod-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: INFO
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: WARN
  REDIS_DB:
    value: '1'

mutualize:
  environment: prod

  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: '3.2'
      atleastOldDays: 20
      sha: d2d3fd298cfbdf1f9d089a42f686314d6407a928aa9a4328a614ddf907758865

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 2
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag '3.29'
      atleastOldDays: 20
      sha: 00e0185eb7d6ed008614d9b180a4b7152d1c3c101b6ae6f8652680d3d8af295d

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: prod
      PGSCHEMA:
        value: prod

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,mutualize-prod-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 3.85Gi
        cpu: 1m
      limits:
        memory: 6300Mi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://geoservices.camptocamp.com/print/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 2
    image:
      repository: camptocamp/mapfish-print-logs
      tag: '1.3'
      atleastOldDays: 20
      sha: 19bf574a493f032798438afe2a9f1b2f18e1a12f7df0a1509a49ddc03e048cd2

    env:
      REDIS_DB:
        value: '2'

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: '1.17'
      atleastOldDays: 20
      sha: 8668ba490635898ed1f5dba794d8b8c18d65c7b734818fa639ec3a0575a5563d

    mainConfig:
      redis:
        db: 3

    env:
      REDIS_DB:
        value: '3'

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,mutualize-prod-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 188Mi
        cpu: 15m
      limits:
        memory: 340Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 110.1Mi
        cpu: 3.1m
      limits:
        memory: 240Mi

ingress:
  hostsGroups:
    - name: main
      hosts:
        - geoservices.camptocamp.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    - name: test
      hosts:
        - mutualize.apps.gs-ch-dev.camptocamp.com
        - mutualize.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize.apps.green.gs-ch-dev.camptocamp.com
