global:
  configMapNameOverride:
    env: mutualize-int-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: DEBUG
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: INFO
  REDIS_DB:
    value: '4'

mutualize:
  environment: int

  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: '3.2'
      sha: ebcb727774b565c7358ac1bd6575e8f0aebdf7c62d3f5684936925c3fa10bb82

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag '3.28' # camptocamp/mapfish_print
      sha: 041e04149b30d82a884fb3d24e3450e197b7192f542672fa3854fd72aae326dc

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: int
      LOG_LEVEL:
        value: DEBUG
      PGSCHEMA:
        value: int

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 2.43Gi
        cpu: 1m
      limits:
        memory: 3Gi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/print/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish-print-logs
      tag: '1.3'
      sha: 98df81c16f439911b87398f375a48b829e3f4527f799f17c09b8819834104464

    env:
      REDIS_DB:
        value: '5'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: master
      sha: d3f9cadde2f9df96aedd949eb8fe47f9ac8b7f18fd575804f65652c67b4db919

    env:
      REDIS_DB:
        value: '6'
      C2C_AUTH_GITHUB_PROXY_URL:
        value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/redirect
      C2C_AUTH_GITHUB_CLIENT_ID:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_ID_INT
      C2C_AUTH_GITHUB_CLIENT_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_SECRET_INT
      C2C_AUTH_GITHUB_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_SECRET_INT
      TILECLOUD_CHAIN_SESSION_SECRET:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SECRET_INT
      TILECLOUD_CHAIN_SESSION_SALT:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SALT_INT

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 150Mi
        cpu: 15m
      limits:
        memory: 300Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 140Mi
        cpu: 3.1m
      limits:
        # memory: 210Mi
        memory: 250Mi

  redirect:
    image:
      repository: camptocamp/redirect
      tag: latest
      sha: 72d880fb5b23dabc11f98974eda1f68beac35d3a691691059c23178a8f53af3b

    resources:
      requests:
        memory: 101.1Mi
        cpu: 1.1m
      limits:
        memory: 202.2Mi

ingress:
  hostsGroups:
    - name: test
      hosts:
        - mutualize-int.apps.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.green.gs-ch-dev.camptocamp.com
