global:
  configMapNameOverride:
    env: mutualize-int-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: DEBUG
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: INFO
  REDIS_DB:
    value: '4'

mutualize:
  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: latest
      sha: 1c913f14cb70716ec3f9c400b1f49f40bd073a520df6f7f970a855adece59acb

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag latest
      sha: 5fdb12a2c566189c804e5e95ebb8d7e2ba9899f6ed663c6b627a05e3bd154776

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: int
      LOG_LEVEL:
        value: DEBUG
      PGSCHEMA:
        value: int

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 2.43Gi
        cpu: 1m
      limits:
        memory: 3Gi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish-print-logs
      tag: latest
      sha: 54573e959abd85b5d4d9f4ba68395edb94fe7f3717121a519ed4d7d33daa38fc

    env:
      REDIS_DB:
        value: '5'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: latest
      sha: b10b2d71a77fefe892c49a3497c3b686e3d2ae936396e576c3e4753c504828a6

    env:
      REDIS_DB:
        value: '6'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 150Mi
        cpu: 15m
      limits:
        memory: 300Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 140Mi
        cpu: 3.1m
      limits:
        memory: 210Mi

  ingress:
    hosts:
      - name: test
        host: mutualize-int.apps.gs-ch-dev.camptocamp.com
        tls:
          secretName: test-print-int-tls
      - name: blue
        host: mutualize-int.apps.blue.gs-ch-dev.camptocamp.com
        tls:
          secretName: blue-print-int-tls
      - name: green
        host: mutualize-int.apps.green.gs-ch-dev.camptocamp.com
        tls:
          secretName: green-print-int-tls
