global:
  configMapNameOverride:
    env: mutualize-int-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: DEBUG
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: INFO
  REDIS_DB:
    value: '4'

mutualize:
  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: latest
      sha: af7e5b7343c9aab3d34d5325520b14fc0c5bd12a99147477fcc9bbfa740002e4

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag latest
      sha: 501ce5aa4ef2d482aefe5cb352892a1139ffc0332913a6c398a323ecff313a98

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: int
      LOG_LEVEL:
        value: DEBUG
      PGSCHEMA:
        value: int

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 2.43Gi
        cpu: 1m
      limits:
        memory: 3Gi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish-print-logs
      tag: latest
      sha: b33c279a422b9f8c419d7cce6ab8f2c620334e8538f8f5674e018b1fce4265fa

    env:
      REDIS_DB:
        value: '5'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: latest
      sha: 01f28b346c6bb7c0a6dcd63403dcc5ddab16e2fc6b71279faabf163e95996dc0

    env:
      REDIS_DB:
        value: '6'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 150Mi
        cpu: 15m
      limits:
        memory: 300Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 140Mi
        cpu: 3.1m
      limits:
        memory: 210Mi

ingress:
  hostsGroups:
    - name: test
      hosts:
        - mutualize-int.apps.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.green.gs-ch-dev.camptocamp.com
