global:
  configMapNameOverride:
    env: mutualize-prod-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: INFO
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: WARN
  REDIS_DB:
    value: '1'

mutualize:
  environment: prod

  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: '3.2'
      atleastOldDays: 20
      sha: de6cb3a6c23894e456f24aac537c9e7c657be03b619cd19b8b8029b93453a70a

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 2
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag '3.29' # camptocamp/mapfish_print
      atleastOldDays: 20
      sha: 71d33e938937d6c91380833c5c1be11a43b8027661b64f844b92638f8c63bfb7

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: prod
      PGSCHEMA:
        value: prod

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,mutualize-prod-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 3.85Gi
        cpu: 1m
      limits:
        memory: 6300Mi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://geoservices.camptocamp.com/print/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 2
    image:
      repository: camptocamp/mapfish-print-logs
      tag: '1.3'
      atleastOldDays: 20
      sha: 44cadbb9122e070d3845db169f9c7915d43f6dbf3f54703e355b49e8bbdfeba2

    env:
      REDIS_DB:
        value: '2'

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: '1.17'
      atleastOldDays: 20
      sha: a9ba00407851bdf3046a6b2769dc6d85de8fa59062562827a7a6bc981e0df967

    mainConfig:
      redis:
        db: 3

    env:
      REDIS_DB:
        value: '3'
      C2C_AUTH_GITHUB_PROXY_URL:
        value: https://geoservices.camptocamp.com/redirect
      C2C_AUTH_GITHUB_CLIENT_ID:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_ID_PROD
      C2C_AUTH_GITHUB_CLIENT_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_SECRET_PROD
      C2C_AUTH_GITHUB_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_SECRET_PROD
      TILECLOUD_CHAIN_SESSION_SECRET:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SECRET_PROD
      TILECLOUD_CHAIN_SESSION_SALT:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SALT_PROD

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,mutualize-prod-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 188Mi
        cpu: 15m
      limits:
        memory: 340Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 110.1Mi
        cpu: 3.1m
      limits:
        memory: 240Mi

  redirect:
    image:
      repository: camptocamp/redirect
      tag: latest # camptocamp/redirect
      atleastOldDays: 20

    resources:
      requests:
        memory: 100.1Mi
        cpu: 1.1m
      limits:
        memory: 200.2Mi

ingress:
  hostsGroups:
    - name: main
      hosts:
        - geoservices.camptocamp.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    - name: test
      hosts:
        - mutualize.apps.gs-ch-dev.camptocamp.com
        - mutualize.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize.apps.green.gs-ch-dev.camptocamp.com
