global:
  configMapNameOverride:
    env: mutualize-int-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: DEBUG
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: INFO
  REDIS_DB:
    value: '4'

mutualize:
  environment: int

  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: '3.2'
      sha: 9e0fcc5d2ed1256feaa90f5846f06c7895dc4ab821a364cb7f53dbf8c93268e3

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag '3.28' # camptocamp/mapfish_print
      sha: 694547a22cce65ac3596aa4696efd438acba9abbd5af40de10f5bdae6284918b

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: int
      LOG_LEVEL:
        value: DEBUG
      PGSCHEMA:
        value: int

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 2.43Gi
        cpu: 1m
      limits:
        memory: 3Gi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/print/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish-print-logs
      tag: '1.3'
      sha: c06bcfb2684213d3a5e7bc84f6164af6900c4c7016cb95a88a8f4284d382e01d

    env:
      REDIS_DB:
        value: '5'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: '1.13' # camptocamp/tilecloud-chain
      sha: 36adb4676f3269a6204e345395ee265d5c871af5ea3e22fbc6d0fb7bf84e4305

    env:
      REDIS_DB:
        value: '6'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 150Mi
        cpu: 15m
      limits:
        memory: 300Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 140Mi
        cpu: 3.1m
      limits:
        # memory: 210Mi
        memory: 250Mi

  redirect:
    image:
      repository: camptocamp/redirect
      tag: 'latest' # camptocamp/redirect

ingress:
  hostsGroups:
    - name: test
      hosts:
        - mutualize-int.apps.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.green.gs-ch-dev.camptocamp.com
