global:
  configMapNameOverride:
    env: mutualize-int-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: DEBUG
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: INFO
  REDIS_DB:
    value: '4'

mutualize:
  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: latest
      sha: 6f5843f69a55cab93ea54e885b63786057ac027e1a317590dfbcea63e5def8f0

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag latest
      sha: 7345e1a780370c4dab3726cf060a0dbb812c56927af94a4b4ab79aa5a8af5672

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: int
      LOG_LEVEL:
        value: DEBUG
      PGSCHEMA:
        value: int

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 2.43Gi
        cpu: 1m
      limits:
        memory: 3Gi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/print/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish-print-logs
      tag: latest
      sha: 2a8f2cfa4c6ee697fab5f1404b5b875e3bdabf861b5b562ccd476b863e6c366f

    env:
      REDIS_DB:
        value: '5'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: latest
      sha: 6a94d39adab3b6579611c0d442e8341c3de6083cb674204b1c0ccf1de2b8b06d

    env:
      REDIS_DB:
        value: '6'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 150Mi
        cpu: 15m
      limits:
        memory: 300Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 140Mi
        cpu: 3.1m
      limits:
        memory: 210Mi

ingress:
  hostsGroups:
    - name: test
      hosts:
        - mutualize-int.apps.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.green.gs-ch-dev.camptocamp.com
