global:
  configMapNameOverride:
    env: mutualize-int-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: DEBUG
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: INFO
  REDIS_DB:
    value: '4'

mutualize:
  environment: int

  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: '3.2'
      sha: 37ea88585c632414853f9fe3b2cd883bb678c1431efef7de5cfdf851356a17d8

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag '3.28' # camptocamp/mapfish_print
      sha: 99a6b918293814b1263cf113a8ccb763d0068c4743250e1044f109e195b4ffa4

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: int
      LOG_LEVEL:
        value: DEBUG
      PGSCHEMA:
        value: int

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 2.43Gi
        cpu: 1m
      limits:
        memory: 3Gi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/print/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 1
    image:
      repository: camptocamp/mapfish-print-logs
      tag: '1.3'
      sha: f3cea73bb89c57d239cc6a0949d8dbb1ffa640ddd3944efad02d757b6c05467e

    env:
      REDIS_DB:
        value: '5'

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: master
      sha: 94e3a1fe0393488c63590dfc56f3e322a275a2e27c0afb1645c8e958d70b2eb8

    env:
      REDIS_DB:
        value: '6'
      C2C_AUTH_GITHUB_PROXY_URL:
        value: https://mutualize-int.apps.gs-ch-dev.camptocamp.com/redirect
      C2C_AUTH_GITHUB_CLIENT_ID:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_ID_INT
      C2C_AUTH_GITHUB_CLIENT_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_SECRET_INT
      C2C_AUTH_GITHUB_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_SECRET_INT
      TILECLOUD_CHAIN_SESSION_SECRET:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SECRET_INT
      TILECLOUD_CHAIN_SESSION_SALT:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SALT_INT

    annotations:
      reloader.stakater.com/auto: mutualize-int-env,mutualize-int,mutualize-int-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 150Mi
        cpu: 15m
      limits:
        memory: 300Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 140Mi
        cpu: 3.1m
      limits:
        # memory: 210Mi
        memory: 250Mi

  redirect:
    image:
      repository: camptocamp/redirect
      tag: latest
      sha: ec51f92c939e3fe13fc1988d5f5a5833d292e09f12c07a8aa36e076bc73699c6

    resources:
      requests:
        memory: 101.1Mi
        cpu: 1.1m
      limits:
        memory: 202.2Mi

ingress:
  hostsGroups:
    - name: test
      hosts:
        - mutualize-int.apps.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize-int.apps.green.gs-ch-dev.camptocamp.com
