global:
  configMapNameOverride:
    env: mutualize-prod-env

config-env-base: &config-env-base
  SENTRY_CLIENT_ENVIRONMENT:
    value: int
  LOG_LEVEL:
    value: INFO
  C2CWSGIUTILS_LOG_LEVEL:
    value: INFO
  GUNICORN_LOG_LEVEL:
    value: WARN
  OTHER_LOG_LEVEL:
    value: WARN
  REDIS_DB:
    value: '1'

mutualize:
  environment: prod

  config:
    replicaCount: 1
    image: &config-image
      repository: camptocamp/shared_config_manager
      tag: '3.2'
      atleastOldDays: 20
      sha: fe97caab814f2157c7ccbf6ec0b44f8475f6cf00b069b9b43107008ff86075cc

    env:
      <<: *config-env-base

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod

    resources:
      requests:
        memory: 150.1Mi
        cpu: 6m
      limits:
        memory: 256Mi

  print:
    replicaCount: 2
    image:
      repository: camptocamp/mapfish_print
      tag: &print-tag '3.29' # camptocamp/mapfish_print
      atleastOldDays: 20
      sha: c686b037e49d66af246544cbc6652a3846d5213ee2ee2d6dbf65786fd9b04d4a

    env:
      SENTRY_RELEASE:
        value: *print-tag
      SENTRY_ENVIRONMENT:
        value: prod
      PGSCHEMA:
        value: prod

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,mutualize-prod-print,database,gmf-blob-storage

    resources:
      requests:
        memory: 3.85Gi
        cpu: 1m
      limits:
        memory: 6300Mi

    config: &config
      image: *config-image
      env:
        <<: *config-env-base
        MUTUALIZED_PRINT_URL:
          value: https://geoservices.camptocamp.com/print/print/
      resources:
        requests:
          memory: 38Mi
          cpu: 1.1m
        limits:
          memory: 1024Mi

  logs:
    replicaCount: 2
    image:
      repository: camptocamp/mapfish-print-logs
      tag: '1.3'
      atleastOldDays: 20
      sha: 085d86404884b85c40074c3db5daf9da7041c85a8c9c30156be903b662b79d74

    env:
      REDIS_DB:
        value: '2'

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,database

    resources:
      requests:
        cpu: 2m
        memory: 107.5Mi
      limits:
        memory: 128Mi

  tilecloudchain: &tilecloudchain
    image:
      repository: camptocamp/tilecloud-chain
      tag: '1.17'
      atleastOldDays: 20
      sha: b2ef0dec70d6a68d528b69ab8f89b82d69d8b8b5f4977bfb6a9f417fe46b93f1

    mainConfig:
      redis:
        db: 3

    env:
      REDIS_DB:
        value: '3'
      C2C_AUTH_GITHUB_PROXY_URL:
        value: https://geoservices.camptocamp.com/redirect
      C2C_AUTH_GITHUB_CLIENT_ID:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_ID_PROD
      C2C_AUTH_GITHUB_CLIENT_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_CLIENT_SECRET_PROD
      C2C_AUTH_GITHUB_SECRET:
        type: secret
        name: secrets
        key: C2C_AUTH_GITHUB_SECRET_PROD
      TILECLOUD_CHAIN_SESSION_SECRET:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SECRET_PROD
      TILECLOUD_CHAIN_SESSION_SALT:
        type: secret
        name: secrets
        key: TILECLOUD_CHAIN_SESSION_SALT_PROD

    annotations:
      reloader.stakater.com/auto: mutualize-prod-env,mutualize-prod,mutualize-prod-tcc-main-config,gmf-blob-storage

    config: *config

    resources:
      requests:
        memory: 188Mi
        cpu: 15m
      limits:
        memory: 340Mi

  tilecloudchainSlave:
    <<: *tilecloudchain

    resources:
      requests:
        memory: 110.1Mi
        cpu: 3.1m
      limits:
        memory: 240Mi

  redirect:
    image:
      repository: camptocamp/redirect
      tag: latest
      atleastOldDays: 20
      sha: b922771a6e7c03aa5fd73a3eaa42384556f38fbc48ddb5761fd01aebad0f8750

    resources:
      requests:
        memory: 100.1Mi
        cpu: 1.1m
      limits:
        memory: 200.2Mi

ingress:
  hostsGroups:
    - name: main
      hosts:
        - geoservices.camptocamp.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    - name: test
      hosts:
        - mutualize.apps.gs-ch-dev.camptocamp.com
        - mutualize.apps.blue.gs-ch-dev.camptocamp.com
        - mutualize.apps.green.gs-ch-dev.camptocamp.com
