extends:
  - eslint:recommended
env:
  es6: true
  jquery: true
  jasmine: true
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  no-console: 0
  comma-dangle: 0
  import/no-unresolved: 0
  valid-jsdoc: 0
  max-len:
    - error
    - code: 110
      ignoreComments: true
