apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mapserver.fullname" . }}
  labels:
{{ include "mapserver.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "mapserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "mapserver.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "mapserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.config.enable }}
      initContainers:
        - name: mapserver-config
          image: "{{ .Values.config.image.repository }}:{{ .Values.config.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['bash', '-c', 'cp -a /etc/mapserver/* /etc/mapserver-volume/']
          volumeMounts:
            - mountPath: /etc/mapserver-volume
              name: configs
          env:
            {{- range $name, $value := .Values.config.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $name, $value := .Values.config.configMap }}
            - name: {{ $name | quote }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $value.name | quote }}
                  key: {{ $value.key | quote }}
            {{- end }}
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.config.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $name, $value := .Values.configMap }}
            - name: {{ $name | quote }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $value.name | quote }}
                  key: {{ $value.key | quote }}
            {{- end }}
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/mapserver
              name: configs
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.apacheExporter.enabled }}
        - name: apache-exporter
          image: "{{ .Values.apacheExporter.image.repository }}:{{ .Values.apacheExporter.image.tag }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - '--scrape_uri=http://{{ include "mapserver.fullname" . }}/server-status-remote?auto'
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: prometheus
              containerPort: 9117
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: prometheus
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.apacheExporter.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: configs
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{-   if .Values.affinity }}
      {{      toYaml .Values.affinity | indent 2 }}
      {{-   else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "mapserver.name" . }}
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
