geomapfish:
  geoportal:
    redis:
      host: redis

    configMapNameOverride: &configMapNameOverride
      env: gmf-demo-geomapfish-env
      secret: gmf-demo-geomapfish-secret

    config: &config
      image:
        repository: camptocamp/geomapfishdemo-config
        tag: prod-2-7

  mapserver:
    configMapNameOverride: *configMapNameOverride
    config: *config

  qgisserver:
    configMapNameOverride: *configMapNameOverride
    config: *config
