geomapfish:
  geoportal:
    image:
      repository: camptocamp/geomapfishapp-geoportal
      tag: 2.7
    resources:
      limits:
        memory: 400Mi
      requests:
        memory: 272Mi
        cpu: 88m

    configMapNameOverride:
      env: gmf-demo-geomapfish-env
      secret: gmf-demo-geomapfish-secret
    env:
      PRINT_URL:
        value: print-url

    config: &config
      image:
        repository: camptocamp/demo-config
        tag: prod-2-7
      resources:
        limits:
          memory: 2Mi
        requests:
          memory: 1Mi
          cpu: 1m

    alembic:
      image:
        repository: camptocamp/geomapfishapp-geoportal
        tag: 2.7
      resources:
        limits:
          memory: 2Mi
        requests:
          memory: 1Mi
          cpu: 1m

    tools:
      image:
        repository: camptocamp/geomapfishapp-tools
        tag: 2.7
      resources:
        limits:
          memory: 2Mi
        requests:
          memory: 1Mi
          cpu: 1m

    dbstats:
      image:
        repository: camptocamp/c2cwsgiutils
        tag: master
      resources:
        limits:
          memory: 2Mi
        requests:
          memory: 1Mi
          cpu: 1m
      schemas:
        - main
        - static

  mapserver:
    image:
      repository: camptocamp/mapserver
      tag: 7.6
    resources:
      requests:
        memory: 111.5Mi
        cpu: 4m
      limits:
        memory: 700Mi
    configMapNameOverride:
      env: prod-2-6-geomapfish-env
    config: *config
    apacheExporter: &apacheExporter
      resources:
        limits:
          memory: 2Mi
        requests:
          memory: 1Mi
          cpu: 1m

  qgisserver:
    image:
      repository: camptocamp/geomapfish-qgisserver
      tag: gmf2.7-qgis3.20
    resources:
      requests:
        memory: 114Mi
        cpu: 12.5m
      limits:
        memory: 300Mi
    configMapNameOverride:
      env: prod-2-6-geomapfish-env
    config: *config
    apacheExporter: *apacheExporter

  postgresql:
    schema: main
    staticSchema: static
