#!/usr/bin/env bash

BRANCH_NAME=update-images-hash-${RANDOM}
git checkout -b ${BRANCH_NAME}
git add --all
git commit --message="Update the images hash"
git push origin ${BRANCH_NAME}
gopass show gs/ci/github/token/gopass | gh auth login --with-token
gh pr create --fill
