redis:
  # https://redis.io/topics/config
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    maxmemory 64mb
    databases 16

  auth:
    enabled: false

  master:
    resources:
      requests:
        cpu: 37m
        memory: 39.0Mi
      limits:
        memory: 200Mi

  replica:
    replicaCount: 3
    resources:
      requests:
        cpu: 37m
        memory: 39.0Mi
      limits:
        memory: 200Mi

  sentinel:
    enabled: true
    resources:
      requests:
        cpu: 33m
        memory: 8Mi
      limits:
        memory: 16Mi

  pdb:
    create: true
    maxUnavailable: 1

  metrics:
    enabled: true
    sentinel:
      enabled: true
      resources:
        requests:
          memory: 15Mi
          cpu: 6m
        limits:
          memory: 50Mi
    resources:
      requests:
        memory: 15Mi
        cpu: 6m
      limits:
        memory: 50Mi
    prometheusRule:
      enabled: true
