apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-console
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: psql-console
  template:
    metadata:
      name: psql-console
      labels:
        name: psql-console
    spec:
      containers:
        - name: psql-console
          image: ghcr.io/camptocamp/postgres:14-postgis-3
          command:
            - /bin/bash
            - -c
          args:
            - tmux new-session -d && bash
          tty: true
          stdin: true
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 3
            exec:
              command:
                - tmux
                - list-sessions
          env:
            - name: SHELL
              value: /bin/sh
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: database
                  key: hostname
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
              cpu: 1m
